apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-python-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-python-flask
  template:
    metadata:
      labels:
        app: weather-python-flask
    spec:
      containers:
      - name: weather-python-flask
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: ENVIRONMENT
          value: "PRODUCTION"
        - name: PORT
          value: "{{ .Values.service.targetPort }}"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key
              key: API_KEY
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri
              key: MONGODB_URI
        - name: MONGODB_TESTS_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-tests-uri
              key: MONGODB_TESTS_URI
        - name: FLASK_ENV
          value: "production"
