apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::864003978924:role/EKS-ClusterManagementRole
      username: EKS-ClusterManagementRole
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::864003978924:user/terraform-user
      username: terraform-user
      groups:
        - system:masters
