apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::864003978924:role/EKS-ClusterManagementRole
      username: EKS-ClusterManagementRole
      groups:
        - system:masters
    - rolearn: arn:aws:iam::864003978924:role/eks_nodes-eks-node-group-20231116120103300500000008
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::864003978924:user/terraform-user
      username: terraform-user
      groups:
        - system:masters
