# Specify the version of the docker-compose file format
version: "3.9"

services:
  # Define the 'app' service configuration
  app:
    # Build context for the Docker image
    build: ./
    # Mount specified host directories into the container
    volumes:
      - ./logs:/app/logs
      - .:/app
    # Map port 5000 on the host to port 5000 on the container
    ports:
      - '5000:5000'