replicaCount: 1

image:
  repository: 864003978924.dkr.ecr.us-east-1.amazonaws.com/weather-app-repo
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 443
  targetPort: 5000

resources: {}
