# CD Pipeline Configuration
# This pipeline is triggered manually for deployments.
# It deploys the application to Heroku using Docker containers.
name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Heroku CLI
      # Installs the Heroku CLI which is needed for deployments
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh  # Install Heroku CLI

    - name: Login to Heroku Container registry
      # Logs in to the Heroku Container Registry using the API key
      run: |
        echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and Push Docker image to Heroku
      # Builds a Docker image and pushes it to the Heroku Container Registry
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release Docker image to Heroku
      # Releases the Docker image on Heroku, thereby deploying the app
      run: |
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Fetch Heroku Logs
      run: heroku logs --tail -a ${{ secrets.HEROKU_APP_NAME }}